//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evebury.Gs1.DigitalLink.Segments.MetaData.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evebury.Gs1.DigitalLink.Segments.MetaData.Resource.Descriptor", typeof(Descriptor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Serial Shipping Container Code (SSCC)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{18})&quot;}.
        /// </summary>
        internal static string D00 {
            get {
                return ResourceManager.GetString("D00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Trade Item Number (GTIN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{14})&quot;,&quot;Qualifiers&quot;: [&quot;22&quot;,&quot;10&quot;,&quot;21&quot;,&quot;235&quot;],&quot;Excludes&quot;: [&quot;02&quot;,&quot;03&quot;,&quot;255&quot;,&quot;37&quot;]}.
        /// </summary>
        internal static string D01 {
            get {
                return ResourceManager.GetString("D01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Trade Item Number (GTIN) of contained trade items&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{14})&quot;,&quot;Requires&quot;: [&quot;00&quot;,&quot;37&quot;],&quot;Excludes&quot;: [&quot;01&quot;,&quot;03&quot;]}.
        /// </summary>
        internal static string D02 {
            get {
                return ResourceManager.GetString("D02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Identification of a Made-to-Order (MtO) trade item (GTIN)&quot;,&quot;Regex&quot;: &quot;(\\d{14})&quot;,&quot;Excludes&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;37&quot;]}.
        /// </summary>
        internal static string D03 {
            get {
                return ResourceManager.GetString("D03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Batch or lot number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;03&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D10 {
            get {
                return ResourceManager.GetString("D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Production date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D11 {
            get {
                return ResourceManager.GetString("D11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Due date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;8020&quot;,&quot;415&quot;]}.
        /// </summary>
        internal static string D12 {
            get {
                return ResourceManager.GetString("D12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Packaging date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D13 {
            get {
                return ResourceManager.GetString("D13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Best before date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D15 {
            get {
                return ResourceManager.GetString("D15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Sell by date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D16 {
            get {
                return ResourceManager.GetString("D16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Expiration date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;255&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D17 {
            get {
                return ResourceManager.GetString("D17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Internal product variant&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{2})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D20 {
            get {
                return ResourceManager.GetString("D20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Serial number&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;03&quot;,&quot;8006&quot;],&quot;Excludes&quot;: [&quot;235&quot;]}.
        /// </summary>
        internal static string D21 {
            get {
                return ResourceManager.GetString("D21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Consumer product variant&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D22 {
            get {
                return ResourceManager.GetString("D22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Third Party Controlled, Serialised Extension of Global Trade Item Number (GTIN) (TPX)&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,28})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D235 {
            get {
                return ResourceManager.GetString("D235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Additional product identification assigned by the manufacturer&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D240 {
            get {
                return ResourceManager.GetString("D240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Customer part number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D241 {
            get {
                return ResourceManager.GetString("D241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Made-to-Order variation number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,6})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;03&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D242 {
            get {
                return ResourceManager.GetString("D242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Packaging component number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D243 {
            get {
                return ResourceManager.GetString("D243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Secondary serial number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;,&quot;8006&quot;,&quot;21&quot;]}.
        /// </summary>
        internal static string D250 {
            get {
                return ResourceManager.GetString("D250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Reference to source entity&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D251 {
            get {
                return ResourceManager.GetString("D251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Document Type Identifier (GDTI)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})([!%-?A-Z_a-z\\x22]{0,17})&quot;}.
        /// </summary>
        internal static string D253 {
            get {
                return ResourceManager.GetString("D253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Location Number (GLN) extension component&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;414&quot;]}.
        /// </summary>
        internal static string D254 {
            get {
                return ResourceManager.GetString("D254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Coupon Number (GCN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})(\\d{0,12})&quot;,&quot;Excludes&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;415&quot;,&quot;8006&quot;,&quot;8020&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D255 {
            get {
                return ResourceManager.GetString("D255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Variable count of items (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{0,8})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D30 {
            get {
                return ResourceManager.GetString("D30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Net weight, kilograms (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3100 {
            get {
                return ResourceManager.GetString("D3100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Length or first dimension, metres (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3110 {
            get {
                return ResourceManager.GetString("D3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Width, diameter, or second dimension, metres (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3120 {
            get {
                return ResourceManager.GetString("D3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Depth, thickness, height, or third dimension, metres (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3130 {
            get {
                return ResourceManager.GetString("D3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Area, square metres (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3140 {
            get {
                return ResourceManager.GetString("D3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Net volume, litres (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3150 {
            get {
                return ResourceManager.GetString("D3150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Logistic weight, kilograms&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3300 {
            get {
                return ResourceManager.GetString("D3300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Length or first dimension, metres&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3310 {
            get {
                return ResourceManager.GetString("D3310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Width, diameter, or second dimension, metres&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3320 {
            get {
                return ResourceManager.GetString("D3320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Depth, thickness, height, or third dimension, metres&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3330 {
            get {
                return ResourceManager.GetString("D3330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Area, square metres&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3340 {
            get {
                return ResourceManager.GetString("D3340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Logistic volume, litres&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3350 {
            get {
                return ResourceManager.GetString("D3350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Kilograms per square metre&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;01&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3370 {
            get {
                return ResourceManager.GetString("D3370", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Count of trade items or trade item pieces contained in a logistic unit&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,8})&quot;,&quot;Requires&quot;: [&quot;00&quot;,&quot;02&quot;,&quot;00&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D37 {
            get {
                return ResourceManager.GetString("D37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Applicable amount payable or Coupon value, local currency&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,15})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;255&quot;,&quot;8020&quot;,&quot;415&quot;],&quot;Excludes&quot;: [&quot;8111&quot;]}.
        /// </summary>
        internal static string D3900 {
            get {
                return ResourceManager.GetString("D3900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Applicable amount payable with ISO currency code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})(\\d{1,15})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;8020&quot;,&quot;415&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3910 {
            get {
                return ResourceManager.GetString("D3910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Applicable amount payable, single monetary area (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,15})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;30&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3920 {
            get {
                return ResourceManager.GetString("D3920", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Applicable amount payable with ISO currency code (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})(\\d{1,15})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;30&quot;],&quot;Excludes&quot;: []}.
        /// </summary>
        internal static string D3930 {
            get {
                return ResourceManager.GetString("D3930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Percentage discount of a coupon&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{4})&quot;,&quot;MaxElements&quot;: 4,&quot;Requires&quot;: [&quot;255&quot;],&quot;Excludes&quot;: [&quot;8111&quot;]}.
        /// </summary>
        internal static string D3940 {
            get {
                return ResourceManager.GetString("D3940", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Amount Payable per unit of measure single monetary area (variable measure trade item)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;MaxElements&quot;: 6,&quot;Requires&quot;: [&quot;30&quot;],&quot;Excludes&quot;: [&quot;8005&quot;]}.
        /// </summary>
        internal static string D3950 {
            get {
                return ResourceManager.GetString("D3950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Customers purchase order number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;}.
        /// </summary>
        internal static string D400 {
            get {
                return ResourceManager.GetString("D400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Identification Number for Consignment (GINC)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;}.
        /// </summary>
        internal static string D401 {
            get {
                return ResourceManager.GetString("D401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Shipment Identification Number (GSIN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{17})&quot;}.
        /// </summary>
        internal static string D402 {
            get {
                return ResourceManager.GetString("D402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Routing code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D403 {
            get {
                return ResourceManager.GetString("D403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship to / Deliver to Global Location Number (GLN)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;}.
        /// </summary>
        internal static string D410 {
            get {
                return ResourceManager.GetString("D410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Bill to / Invoice to Global Location Number (GLN)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;}.
        /// </summary>
        internal static string D411 {
            get {
                return ResourceManager.GetString("D411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Purchased from Global Location Number (GLN)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;}.
        /// </summary>
        internal static string D412 {
            get {
                return ResourceManager.GetString("D412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship for / Deliver for - Forward to Global Location Number (GLN)&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;}.
        /// </summary>
        internal static string D413 {
            get {
                return ResourceManager.GetString("D413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Identification of a physical location - Global Location Number (GLN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;,&quot;Qualifiers&quot;: [&quot;254&quot;,&quot;7040&quot;]}.
        /// </summary>
        internal static string D414 {
            get {
                return ResourceManager.GetString("D414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Location Number (GLN) of the invoicing party&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;,&quot;Qualifiers&quot;: [&quot;8020&quot;],&quot;Requires&quot;: [&quot;8020&quot;]}.
        /// </summary>
        internal static string D415 {
            get {
                return ResourceManager.GetString("D415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Location Number (GLN) of the production or service location&quot;,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;}.
        /// </summary>
        internal static string D416 {
            get {
                return ResourceManager.GetString("D416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Party Global Location Number (GLN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;,&quot;Qualifiers&quot;: [&quot;7040&quot;]}.
        /// </summary>
        internal static string D417 {
            get {
                return ResourceManager.GetString("D417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship to / Deliver to postal code within a single postal authority&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Excludes&quot;: [&quot;421&quot;]}.
        /// </summary>
        internal static string D420 {
            get {
                return ResourceManager.GetString("D420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship to / Deliver to postal code with ISO country code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})([!%-?A-Z_a-z\\x22]{1,9})&quot;,&quot;Excludes&quot;: [&quot;4307&quot;]}.
        /// </summary>
        internal static string D421 {
            get {
                return ResourceManager.GetString("D421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country of origin of a trade item&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;],&quot;Excludes&quot;: [&quot;426&quot;]}.
        /// </summary>
        internal static string D422 {
            get {
                return ResourceManager.GetString("D422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country of initial processing&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:\\d{3}){1,5})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: [&quot;426&quot;]}.
        /// </summary>
        internal static string D423 {
            get {
                return ResourceManager.GetString("D423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country of processing&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: [&quot;426&quot;]}.
        /// </summary>
        internal static string D424 {
            get {
                return ResourceManager.GetString("D424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country of disassembly&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:\\d{3}){1,5})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;],&quot;Excludes&quot;: [&quot;426&quot;]}.
        /// </summary>
        internal static string D425 {
            get {
                return ResourceManager.GetString("D425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country covering full process chain&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D426 {
            get {
                return ResourceManager.GetString("D426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Country subdivision Of origin&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,3})&quot;,&quot;Requires&quot;: [&quot;422&quot;,&quot;01&quot;,&quot;422&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D427 {
            get {
                return ResourceManager.GetString("D427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to company name&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4300 {
            get {
                return ResourceManager.GetString("D4300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to contact&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4301 {
            get {
                return ResourceManager.GetString("D4301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to address line 1&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4302 {
            get {
                return ResourceManager.GetString("D4302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to address line 2&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;4302&quot;,&quot;00&quot;]}.
        /// </summary>
        internal static string D4303 {
            get {
                return ResourceManager.GetString("D4303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to suburb&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4304 {
            get {
                return ResourceManager.GetString("D4304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to locality&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4305 {
            get {
                return ResourceManager.GetString("D4305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to region&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4306 {
            get {
                return ResourceManager.GetString("D4306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to country code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([A-Z0-9]{2})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4307 {
            get {
                return ResourceManager.GetString("D4307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to telephone number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4308 {
            get {
                return ResourceManager.GetString("D4308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Ship-to / Deliver-to GEO location&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{20})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4309 {
            get {
                return ResourceManager.GetString("D4309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to company name&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4310 {
            get {
                return ResourceManager.GetString("D4310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to contact&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4311 {
            get {
                return ResourceManager.GetString("D4311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to address line 1&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4312 {
            get {
                return ResourceManager.GetString("D4312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to address line 2&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;4312&quot;,&quot;00&quot;]}.
        /// </summary>
        internal static string D4313 {
            get {
                return ResourceManager.GetString("D4313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to suburb&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4314 {
            get {
                return ResourceManager.GetString("D4314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to locality&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4315 {
            get {
                return ResourceManager.GetString("D4315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to region&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4316 {
            get {
                return ResourceManager.GetString("D4316", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to country code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([A-Z0-9]{2})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4317 {
            get {
                return ResourceManager.GetString("D4317", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to postal code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4318 {
            get {
                return ResourceManager.GetString("D4318", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Return-to telephone number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4319 {
            get {
                return ResourceManager.GetString("D4319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Service code description&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,35})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4320 {
            get {
                return ResourceManager.GetString("D4320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Dangerous goods flag&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([01])&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4321 {
            get {
                return ResourceManager.GetString("D4321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Authority to leave&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([01])&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4322 {
            get {
                return ResourceManager.GetString("D4322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Signature required flag&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([01])&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4323 {
            get {
                return ResourceManager.GetString("D4323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Not before delivery date time (YYMMDDhhmm)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{10})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4324 {
            get {
                return ResourceManager.GetString("D4324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Not after delivery date time (YYMMDDhhmm)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{10})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4325 {
            get {
                return ResourceManager.GetString("D4325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Release date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D4326 {
            get {
                return ResourceManager.GetString("D4326", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Maximum temperature in Fahrenheit (expressed in hundredths of degrees)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6}[-]?)&quot;,&quot;Requires&quot;: [&quot;00&quot;],&quot;Excludes&quot;: [&quot;4331&quot;]}.
        /// </summary>
        internal static string D4330 {
            get {
                return ResourceManager.GetString("D4330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Minimum temperature in Celsius (expressed in hundredths of degrees)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6}[-]?)&quot;,&quot;Requires&quot;: [&quot;00&quot;],&quot;Excludes&quot;: [&quot;4332&quot;]}.
        /// </summary>
        internal static string D4333 {
            get {
                return ResourceManager.GetString("D4333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;NATO Stock Number (NSN)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{13})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;,&quot;8006&quot;,&quot;8026&quot;]}.
        /// </summary>
        internal static string D7001 {
            get {
                return ResourceManager.GetString("D7001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;UN/ECE meat carcasses and cuts classification&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7002 {
            get {
                return ResourceManager.GetString("D7002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Expiration date and time (YYMMDDhhmm)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{10})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7003 {
            get {
                return ResourceManager.GetString("D7003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Active potency&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{0,4})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;10&quot;]}.
        /// </summary>
        internal static string D7004 {
            get {
                return ResourceManager.GetString("D7004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Catch area&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,12})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7005 {
            get {
                return ResourceManager.GetString("D7005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;First freeze date (YYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7006 {
            get {
                return ResourceManager.GetString("D7006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Harvest date (YYMMDD[YYMMDD])&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})(\\d{6})?&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7007 {
            get {
                return ResourceManager.GetString("D7007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Species for fishery purposes&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,3})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7008 {
            get {
                return ResourceManager.GetString("D7008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Fishing gear type&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,10})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7009 {
            get {
                return ResourceManager.GetString("D7009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Production method&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,2})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7010 {
            get {
                return ResourceManager.GetString("D7010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Test by date (YYMMDD[hhmm])&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})(\\d{4})?&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7011 {
            get {
                return ResourceManager.GetString("D7011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Refurbishment lot ID&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;416&quot;,&quot;01&quot;,&quot;416&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D7020 {
            get {
                return ResourceManager.GetString("D7020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Functional status&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D7021 {
            get {
                return ResourceManager.GetString("D7021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Revision status&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;7021&quot;,&quot;01&quot;,&quot;7021&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D7022 {
            get {
                return ResourceManager.GetString("D7022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Individual Asset Identifier (GIAI) of an assembly&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;}.
        /// </summary>
        internal static string D7023 {
            get {
                return ResourceManager.GetString("D7023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Number of processor with three-digit ISO country code&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{3})([!%-?A-Z_a-z\\x22]{1,27})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D7030 {
            get {
                return ResourceManager.GetString("D7030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;GS1 UIC with Extension 1 and Importer index&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d)([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])([!%-?A-Z_a-z\\x22])&quot;}.
        /// </summary>
        internal static string D7040 {
            get {
                return ResourceManager.GetString("D7040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;UN/CEFACT freight unit type&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,4})&quot;,&quot;Requires&quot;: [&quot;00&quot;]}.
        /// </summary>
        internal static string D7041 {
            get {
                return ResourceManager.GetString("D7041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Germany PZN&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D710 {
            get {
                return ResourceManager.GetString("D710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - France CIP&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D711 {
            get {
                return ResourceManager.GetString("D711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Spain CN&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D712 {
            get {
                return ResourceManager.GetString("D712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Brasil DRN&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D713 {
            get {
                return ResourceManager.GetString("D713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Portugal AIM&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D714 {
            get {
                return ResourceManager.GetString("D714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - United States of America NDC&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D715 {
            get {
                return ResourceManager.GetString("D715", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Italy AIC&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D716 {
            get {
                return ResourceManager.GetString("D716", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;National Healthcare Reimbursement Number (NHRN) - Costa Rica Sanitary Register Number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D717 {
            get {
                return ResourceManager.GetString("D717", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Certification Reference&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{3,30})&quot;,&quot;MaxElements&quot;: 10,&quot;Requires&quot;: [&quot;01&quot;,&quot;8004&quot;]}.
        /// </summary>
        internal static string D7230 {
            get {
                return ResourceManager.GetString("D7230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Protocol ID&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D7240 {
            get {
                return ResourceManager.GetString("D7240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;AIDC media type&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{2})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;]}.
        /// </summary>
        internal static string D7241 {
            get {
                return ResourceManager.GetString("D7241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Version Control Number (VCN)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,25})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;]}.
        /// </summary>
        internal static string D7242 {
            get {
                return ResourceManager.GetString("D7242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Date of birth (YYYYMMDD)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01]))&quot;,&quot;Requires&quot;: [&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7251&quot;]}.
        /// </summary>
        internal static string D7250 {
            get {
                return ResourceManager.GetString("D7250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Date and time of birth (YYYYMMDDhhmm)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{4}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3])(?:[0-5]\\d))&quot;,&quot;Requires&quot;: [&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7250&quot;]}.
        /// </summary>
        internal static string D7251 {
            get {
                return ResourceManager.GetString("D7251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Biological sex&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1})&quot;,&quot;Requires&quot;: [&quot;8018&quot;]}.
        /// </summary>
        internal static string D7252 {
            get {
                return ResourceManager.GetString("D7252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Family name of person&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7256&quot;,&quot;7259&quot;]}.
        /// </summary>
        internal static string D7253 {
            get {
                return ResourceManager.GetString("D7253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Given name of person&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7256&quot;,&quot;7259&quot;]}.
        /// </summary>
        internal static string D7254 {
            get {
                return ResourceManager.GetString("D7254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Name suffix of person&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,10})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7256&quot;,&quot;7259&quot;]}.
        /// </summary>
        internal static string D7255 {
            get {
                return ResourceManager.GetString("D7255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Full name of person&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,90})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7253&quot;,&quot;7254&quot;,&quot;7255&quot;,&quot;7259&quot;]}.
        /// </summary>
        internal static string D7256 {
            get {
                return ResourceManager.GetString("D7256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Address of person&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,70})&quot;,&quot;Requires&quot;: [&quot;8018&quot;]}.
        /// </summary>
        internal static string D7257 {
            get {
                return ResourceManager.GetString("D7257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Baby birth sequence&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d[/]\\d)&quot;,&quot;Requires&quot;: [&quot;8018&quot;,&quot;7259&quot;]}.
        /// </summary>
        internal static string D7258 {
            get {
                return ResourceManager.GetString("D7258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Baby of family name&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;((?:[!%-?A-Z_a-z\\x22]|%[0-9A-Fa-f][0-9A-Fa-f]%[0-9A-Fa-f][0-9A-Fa-f]){1,40})&quot;,&quot;Requires&quot;: [&quot;8018&quot;],&quot;Excludes&quot;: [&quot;7253&quot;,&quot;7254&quot;,&quot;7255&quot;,&quot;7256&quot;]}.
        /// </summary>
        internal static string D7259 {
            get {
                return ResourceManager.GetString("D7259", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Roll products (width, length, core diameter, direction, splices)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{4})(\\d{5})(\\d{3})(\\d{1})(\\d{1})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D8001 {
            get {
                return ResourceManager.GetString("D8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Cellular mobile telephone identifier&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;}.
        /// </summary>
        internal static string D8002 {
            get {
                return ResourceManager.GetString("D8002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Returnable Asset Identifier (GRAI)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(0)(\\d{13})([!%-?A-Z_a-z\\x22]{0,16})&quot;}.
        /// </summary>
        internal static string D8003 {
            get {
                return ResourceManager.GetString("D8003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Individual Asset Identifier (GIAI)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;,&quot;Qualifiers&quot;: [&quot;7040&quot;]}.
        /// </summary>
        internal static string D8004 {
            get {
                return ResourceManager.GetString("D8004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Price per unit of measure&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{6})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D8005 {
            get {
                return ResourceManager.GetString("D8005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Identification of an individual trade item piece (ITIP)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{14})(\\d{4})&quot;,&quot;Qualifiers&quot;: [&quot;22&quot;,&quot;10&quot;,&quot;21&quot;],&quot;Excludes&quot;: [&quot;01&quot;,&quot;37&quot;]}.
        /// </summary>
        internal static string D8006 {
            get {
                return ResourceManager.GetString("D8006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;International Bank Account Number (IBAN)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,34})&quot;,&quot;Requires&quot;: [&quot;8020&quot;,&quot;415&quot;]}.
        /// </summary>
        internal static string D8007 {
            get {
                return ResourceManager.GetString("D8007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Date and time of production (YYMMDDhh[mm[ss]])&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{2}(?:0\\d|1[0-2])(?:[0-2]\\d|3[01])(?:[01]\\d|2[0-3]))((?:[0-5]\\d)(?:[0-5]\\d)?)?&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;02&quot;]}.
        /// </summary>
        internal static string D8008 {
            get {
                return ResourceManager.GetString("D8008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Optically Readable Sensor Indicator&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,50})&quot;,&quot;Requires&quot;: [&quot;00&quot;,&quot;01&quot;]}.
        /// </summary>
        internal static string D8009 {
            get {
                return ResourceManager.GetString("D8009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Component/Part Identifier (CPID)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([A-Z0-9/#-]{5,30})&quot;,&quot;Qualifiers&quot;: [&quot;8011&quot;]}.
        /// </summary>
        internal static string D8010 {
            get {
                return ResourceManager.GetString("D8010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Component/Part Identifier serial number (CPID SERIAL)&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,12})&quot;,&quot;Requires&quot;: [&quot;8010&quot;]}.
        /// </summary>
        internal static string D8011 {
            get {
                return ResourceManager.GetString("D8011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Software version&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D8012 {
            get {
                return ResourceManager.GetString("D8012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Model Number (GMN)&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,25})&quot;}.
        /// </summary>
        internal static string D8013 {
            get {
                return ResourceManager.GetString("D8013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Highly Individualised Device Registration Identifier (HIDRI)&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,25})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D8014 {
            get {
                return ResourceManager.GetString("D8014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the provider of services&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{18})&quot;,&quot;Qualifiers&quot;: [&quot;8019&quot;],&quot;Excludes&quot;: [&quot;8018&quot;]}.
        /// </summary>
        internal static string D8017 {
            get {
                return ResourceManager.GetString("D8017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Global Service Relation Number (GSRN) to identify the relationship between an organisation offering services and the recipient of services&quot;,&quot;IsPrimary&quot;: true,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{18})&quot;,&quot;Qualifiers&quot;: [&quot;8019&quot;],&quot;Excludes&quot;: [&quot;8017&quot;]}.
        /// </summary>
        internal static string D8018 {
            get {
                return ResourceManager.GetString("D8018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Service Relation Instance Number (SRIN)&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{1,10})&quot;,&quot;Requires&quot;: [&quot;8017&quot;,&quot;8018&quot;]}.
        /// </summary>
        internal static string D8019 {
            get {
                return ResourceManager.GetString("D8019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Payment slip reference number&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,25})&quot;,&quot;Requires&quot;: [&quot;415&quot;]}.
        /// </summary>
        internal static string D8020 {
            get {
                return ResourceManager.GetString("D8020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Identification of pieces of a trade item (ITIP) contained in a logistic unit&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{14})(\\d{4})&quot;,&quot;Requires&quot;: [&quot;00&quot;,&quot;37&quot;],&quot;Excludes&quot;: [&quot;02&quot;,&quot;8006&quot;]}.
        /// </summary>
        internal static string D8026 {
            get {
                return ResourceManager.GetString("D8026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Digital Signature (DigSig)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([0-9A-Za-z_-]{1,90})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;,&quot;8006&quot;,&quot;21&quot;,&quot;8010&quot;,&quot;8011&quot;,&quot;8003&quot;,&quot;8004&quot;,&quot;8017&quot;,&quot;8018&quot;,&quot;00&quot;,&quot;253&quot;,&quot;255&quot;]}.
        /// </summary>
        internal static string D8030 {
            get {
                return ResourceManager.GetString("D8030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Internatinal Mobile Equipment Identity (IMEI)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{15})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;]}.
        /// </summary>
        internal static string D8040 {
            get {
                return ResourceManager.GetString("D8040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Internatinal Mobile Equipment Identity 2 (IMEI2)&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{15})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;,&quot;8040&quot;]}.
        /// </summary>
        internal static string D8041 {
            get {
                return ResourceManager.GetString("D8041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Embedded SIM number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{32})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;,&quot;8040&quot;]}.
        /// </summary>
        internal static string D8042 {
            get {
                return ResourceManager.GetString("D8042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Physical SIM number&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{18,20})&quot;,&quot;Requires&quot;: [&quot;01&quot;,&quot;21&quot;,&quot;8040&quot;]}.
        /// </summary>
        internal static string D8043 {
            get {
                return ResourceManager.GetString("D8043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Coupon code identification for use in North America&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,70})&quot;}.
        /// </summary>
        internal static string D8110 {
            get {
                return ResourceManager.GetString("D8110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Loyalty points of a coupon&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;(\\d{4})&quot;,&quot;Requires&quot;: [&quot;255&quot;]}.
        /// </summary>
        internal static string D8111 {
            get {
                return ResourceManager.GetString("D8111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Positive offer file coupon code identification for use in North America&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,70})&quot;}.
        /// </summary>
        internal static string D8112 {
            get {
                return ResourceManager.GetString("D8112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Extended Packaging URL&quot;,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,70})&quot;,&quot;Requires&quot;: [&quot;01&quot;]}.
        /// </summary>
        internal static string D8200 {
            get {
                return ResourceManager.GetString("D8200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Information mutually agreed between trading partners&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,30})&quot;}.
        /// </summary>
        internal static string D90 {
            get {
                return ResourceManager.GetString("D90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Label&quot;: &quot;Company internal information&quot;,&quot;Attribute&quot;: true,&quot;Separator&quot;: true,&quot;Regex&quot;: &quot;([!%-?A-Z_a-z\\x22]{1,90})&quot;,&quot;MaxElements&quot;: 9}.
        /// </summary>
        internal static string D91 {
            get {
                return ResourceManager.GetString("D91", resourceCulture);
            }
        }
    }
}
